name: CI/CD - Node.js con Docker + GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

   # - name: Ejecutar pruebas
    #  run: npm test

    - name: Autenticarse en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convertir el nombre de usuario a minúsculas
      id: lowercase
      run: echo "repository_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Construir imagen Docker
      run: |
        docker build -t ghcr.io/${{ env.repository_owner }}/reserva-restaurante:latest .

    - name: Subir imagen a GHCR
      run: |
        docker push ghcr.io/${{ env.repository_owner }}/reserva-restaurante:latest

